const ACTION = {
  INIT: "INIT",
  ACCEPT_UUID: "ACCEPT_UUID",
  LANGUAGE_CHANGE: "LANGUAGE_CHANGE",
  SAVE_USER: "SAVE_USER",
  SAVE_LOGIN_NAV: "SAVE_LOGIN_NAV",
  SAVE_POSTLOGIN_NAV: "SAVE_POSTLOGIN_NAV",
  SAVE_CART_TOKEN: "SAVE_CART_TOKEN",
};
export default ACTION;
